### ISSUE TITLE
User should be sent to FAQ/tool tip for insufficent funds pop-up modal

### ISSUE THREAD

**Issue by improvethings** [tokenocean/digideeds#4]
This is likely a most common error for non-techies trying us out for the first time, so the error should point to a video walk through or very clear instructions. Speak to Katie, she might offer to help us by providing this for us.

**Comment by improvethings** [comment]
We should also note in the error "You need at least 1000 sats or 0.0001 L-BTC in your wallet to begin" (stating minimums so users don't try a lower amount)

**Comment by secondl1ght** [comment]
Done, I added more details directing the user to check out the FAQ page to learn how to add fund to their wallet and also noted the min amount required in the modal.
