### ISSUE TITLE
Remove Fire protection from the form fields

### ISSUE THREAD

**Issue by improvethings** [tokenocean/digideeds#5]

**Comment by secondl1ght** [comment]
What is fire protection?

**Comment by improvethings** [comment]
It's something not used in Canada or US AFAIK, it can be removed. 
Instead, can you add an optional "Realtor Disclosure" text box that appears from a "Are you a realtor?" check box if they click yes, as one of our users is a realtor who wants to enter her legalese as required. If they say no, the listing should be listed as "Private sale"

**Comment by secondl1ght** [comment]
ok so should I make the 'Realtor Disclosure' field a `required` field? or would there be a case where that could be `null` and the user is still a Realtor?

**Comment by improvethings** [comment]
I think "Are you a realtor" should be required. If not, the NFT would say "Private Sale", if they say yes, it will provide the realtor a text box for their disclosure and the NFT would say "Licensed Realtor Disclosure:" and then whatever they wrote in the text box.

**Comment by secondl1ght** [comment]
Done
