### ISSUE TITLE
Allow user to resize their thumbnail image

### ISSUE THREAD

**Issue by improvethings** [tokenocean/digideeds#6]
User uploaded their favourite photo with text on it, once listed, it cropped it in the wrong place. 

![Screen Shot 2022-04-14 at 11 53 22 AM](https://user-images.githubusercontent.com/16601027/163508969-466f99a1-44ce-448c-bed3-cc918f253853.png)
![Screen Shot 2022-04-14 at 11 49 22 AM](https://user-images.githubusercontent.com/16601027/163508972-344b728d-1316-4956-a14a-ee773e352b75.png)

**Comment by improvethings** [comment]
We have another user reporting the issue that we're cropping and compressing the quality of the thumbnail so that the quality of the image is visibly worse.

**Comment by improvethings** [comment]
To add more complexity to the issue, I'd like to see the images end up as [WebP or AVIF](https://web.dev/uses-webp-images/), shrunk to a reasonable thumbnail size, cropped as the user chooses, and be as lossless yet small in byte size as possible. Hopefully there's a library for that :D

**Comment by secondl1ght** [comment]
posting these here to track for future reference, kris suggested checking these out:

https://github.com/pqina/filepond
https://flatlogic.com/blog/12-javascript-image-manipulation-libraries-for-your-next-web-app/

**Comment by secondl1ght** [comment]
@mightymitel it sounded like you may want to take this task on?

**Comment by secondl1ght** [comment]
also @asoltys mentioned in the call an option of not having the user edit the photo's but instead just allowing the cards on the Market to be whatever size is needed to fit the image, an example of this already in prod is https://mintalio.com/market.

**Comment by secondl1ght** [comment]
The Mintalio option seems like it will be much easier to implement and personally I think it still looks good not having all the cards the same size, so if we can agree on this method then we just need to figure out the compression and reduced quality issue. But if we are OK with the extra dev work and want to integrate the photo editor/preview option then that's also a possibility, it sounded from the artists though that they didn't want their artwork changed at all?

**Comment by secondl1ght** [comment]
@improvethings can you send me this image so I can test?

**Comment by improvethings** [comment]
I've asked the user to send you the original which I see she has done

**Comment by secondl1ght** [comment]
Just pushed a fix so that images will scale to fit inside the card component, we can see what people think and get design feedback and reopen if needed.
