### ISSUE TITLE
Admin page showing as empty/white screen

### ISSUE THREAD

**Issue by improvethings** [tokenocean/digideeds#8]
![Screenshot from 2022-04-20 08-59-06](https://user-images.githubusercontent.com/16601027/164273260-4fb52358-a26b-48fd-8384-06fffd471907.png)

It says "Artist Applications" and then just a white screen

**Comment by secondl1ght** [comment]
I don't think we have the application functionality enabled for digideeds so all users are able to mint right away.

**Comment by improvethings** [comment]
Remove "Admin" from title in headers if functionality is not enabled

**Comment by secondl1ght** [comment]
Done, pushed to staging.
